### ISSUE TITLE
Selecting Raman amplifier in example notebook gives error

### ISSUE THREAD

**Issue by ShrinivasJC** [FastNFT/NFDMLab#1]
https://github.com/FastNFT/NFDMLab/blob/f8afaf699e7bda9e3b30f6dc8baf9312c028eb01/Helpers/widgets.py#L160

The directory name is case sensitive and hence should be 'Data' not 'data'.

**Comment by marbre** [comment]
Already fixed with commit https://github.com/FastNFT/NFDMLab/commit/298969df143ccfb48a31396106e11692bbb17365 on develop.
