### ISSUE TITLE
Failed attempts in performing simulations using NFDMLab in Windows7 environment

### ISSUE THREAD

**Issue by U1poorna** [FastNFT/NFDMLab#2]
![image](https://user-images.githubusercontent.com/79967312/109875596-ac255b00-7c96-11eb-8879-34773c721db2.png)

 .py files **MISSING**  in directory path  [ NFDMLab/Normalization/ ](https://github.com/FastNFT/NFDMLab/tree/master/Normalization) corresponding to 

**Normalization**

.. autoclass:: Normalization.BaseNormalization
    :members:

.. autoclass:: Normalization.Lossless
    :members:
    :special-members:

.. autoclass:: Normalization.Lumped
    :members:
    :special-members:

![NFDMLab_error](https://user-images.githubusercontent.com/79967312/109876941-67022880-7c98-11eb-97ed-dada6166a36d.jpg)

**Comment by U1poorna** [comment]
@xmhk @marbre @ShrinivasJC , please support in resolving this missing .py files in Normalization directory

cc @wahls

**Comment by xmhk** [comment]
Hi @U1poorna ,
I think it's a little confusing to tell where the error is, looking at the images.

Could you tell us:
1. whether you could compile FNFT on your windows environment. If so, could you run the example files (exe files)?
2. after compiling, where is the location of the FNFT library file?
3.  Were you able to  install pyFNFT ?? -- this has a seperate github page: https://github.com/xmhk/FNFTpy and has to be installed separately. If so, can you run the files run_examples.py and run_tests.py?

Best, Christoph

**Comment by U1poorna** [comment]
Hi Christoph,

1. whether you could compile FNFT on your windows environment. If so, could you run the example files (exe files)?
I have followed the procedure mentioned in [FNFT/INSTALL.md](https://github.com/FastNFT/FNFT/blob/master/INSTALL.md) to build via Scoop packet manager, here I could successfully install required tools except
- _scoop install gcc_ command in power shell is giving **error**
![image](https://user-images.githubusercontent.com/79967312/110092573-bdb65200-7dbf-11eb-9a34-488429f5d612.png)

- Since I had this problem of installing gcc using power shell command, so downloaded and installed Cygwin GCC binaries for windows platform from [https://gcc.gnu.org/install/binaries.html](https://gcc.gnu.org/install/binaries.html)

2. after compiling, where is the location of the FNFT library file?
- Unable to build FNFT using the steps mentioned in INSTALL.md
![image](https://user-images.githubusercontent.com/79967312/110096752-4505c480-7dc4-11eb-8512-1f77d5ef9ca5.png)

3. Were you able to install pyFNFT ?? -- this has a seperate github page: https://github.com/xmhk/FNFTpy and has to be installed separately. If so, can you run the files run_examples.py and run_tests.py?
- Yes, I have successfully installed FNFTpy using pip:
_pip install .     # Install system wide
pip install -e .  # Install in editable/development mode_
![image](https://user-images.githubusercontent.com/79967312/110097488-1b00d200-7dc5-11eb-914e-ad6bdbde800f.png)
 
Regards,
Maheshwari

**Comment by U1poorna** [comment]
@xmhk .. https://github.com/FastNFT/NFDMLab/issues/2#issuecomment-791302185  my answers to the questions

**Comment by wahls** [comment]
It seems that your alternative installation of gcc is not working correctly. I am wondering why the installation via scoop has failed. Could it be that you have to update scoops list of packages?

**Comment by U1poorna** [comment]
@wahls , Thanks for the inputs
Okay, if manually installed Cygwin GCC binaries is suspected of not working correctly.. than I will check with other available binaries for windows platform from https://gcc.gnu.org/install/binaries.html.

To the other point, I have checked with updating scoops list of package as well, but the error continues to be seen.
I understand that the url link that _scoop install gcc_ is looking out to install gcc doesn't exist at all..
![image](https://user-images.githubusercontent.com/79967312/110194797-99f71880-7e60-11eb-9d19-c37e6052fa0c.png)

![image](https://user-images.githubusercontent.com/79967312/110194772-53a1b980-7e60-11eb-8d4f-1f55d7a2cc9d.png)

Regards,
Maheshwari

**Comment by U1poorna** [comment]
I could able to compile FNFT, also build library using mingw-w64 GCC binaries.  
FNFT library build pass status for _mingw32-make -j4 test_ command
![image](https://user-images.githubusercontent.com/79967312/110228873-b8294b00-7f2a-11eb-9f78-48a6a4cc2c06.png)


After compiling the location of FNFT library files is _E:\BMS\1Sem\OC\Seminar DWDM\NFDMLab-master\FNFT\build\libfnft.dll_
Edited the function get_lib_path() in auxiliary.py, so to direct to right path of library .dll file (libfnft.dll)

Installed FNFTpy using pip:

- _pip install . # Install system wide_
- _pip install -e . # Install in editable/development mode_

**Comment by U1poorna** [comment]
After compiling FNFT and installing FNFTpy, I could able to run examples using following commands in Spyder (Python 3.8) console

- _import Examples_
- _ex = Examples.BuelowArefIdler2016()_ 
- _[tx_data, rx_data] = ex.run(5)_
- _ex.evaluate_results(tx_data, rx_data)_

![image](https://user-images.githubusercontent.com/79967312/110229347-caa58380-7f2e-11eb-852b-d0f745d24eaa.png)


To perform this exercise, I'm using Anaconda distribution that includes Jupyter package along with Spyder,
**Unable to solve an error seen to command** : _jupyter notebook Notebooks/BuelowArefIdler2016.ipynb_, need your inputs in this error
![image](https://user-images.githubusercontent.com/79967312/110229796-042bbe00-7f32-11eb-9157-ddb4285377ba.png)

**Comment by xmhk** [comment]
Hi  Maheshwari,

looking at the first screenshot, It seems to me that the FNFT library as well as the python wrapper are installed correctly and working.

For the remaining error (second screenshot) -- I think what happened there is that you somehow pasted the source code of the Example Jupyter (Ipython) notebook  into a new notebook.
A Jupyter notebook is a text file in the JSON format which is interpreted by the Jupyter kernel.  It contains the cell structure, annotations, Markdown and also Python code, BUT it is not purely python code. Jupyter expects proper Python code for the Code cells, so it throws that error because in your example it gets code from a different language.

The way to fix you problem is to open to the *.ipynb file (I assume it is the Example1.ipynb file from NFDMLab) and open it from **inside the Jupyter environment**. 

From what I see is that you placed the NFDMLab files on drive E: (E:\BMS\1Sem\OC\Seminar DWDM\NFDMLab-master\), while your Jupyterlab shows most probably the contents of your drive C:.  So you may have to start the Jupyterlab using a different start folder, e.g. on drive E:.

I'm no expert on Anaconda but google may help for this. From my quick search I found this: [https://stackoverflow.com/a/53120527]( https://stackoverflow.com/a/53120527 ), but I can not test as I don't have a Windows machine at hand.

Best, Christoph

**Comment by U1poorna** [comment]
Thanks Christoph, 

Yes, mistake due to inexperience :smile: ... now, I could able to change working directory to current project directory _(E:\BMS\1Sem\OC\Seminar DWDM\NFDMLab-master)_ and interactively run BuelowArefIdler2016... in Jupyter Notebook

![image](https://user-images.githubusercontent.com/79967312/110363108-27f12000-8068-11eb-9101-e414c996be56.png)

Here, I could see _Tx Power Level and other parameter values_ as a outcome of simulation, but for some reason plots are not visible even after multiple attempts of restarting the kernel, than rerunning whole notebook- BuelowArefIdler2016.ipynb

**Comment by xmhk** [comment]
Hi again, 

There seems to be a problem with the plotting backend Jupyter is using. The notebook works fine for me and shows the plot, so it's a little hard to guess what's wrong exactly. My tip would be some unfortunate combination of package versions but I am not sure.
- Can you give the version numbers of 
   - python
   - matplotlib
   - ipython
   - jupyter notebook on your PC?
 - can you look if something suspicious is printed in the command window (from which you start the Jupyter notebook kernel?)

A temporary fix may be that you could replace the line 
`%matplotlib notebook`  in the imports section  with `%matplotlib inline`, which should give you an inline plot which, however, is not dynamic. Maybe this helps already.

Best, Christoph

**Comment by wahls** [comment]
Maybe it is good to know that you do not have to use Jupyter. The examples can be run directly from the Python prompt. See e.g. the first video at [https://fastnft.github.io/NFDMLab/videos.html](https://fastnft.github.io/NFDMLab/videos.html).

**Comment by U1poorna** [comment]
Okay, and with the help of video tutorial- I'm able to run examples directly from the Python prompt and see simulation outcome for different setting options.

I shall close this ticket..., All above inputs helped me a lot, Thanks again for all your kind support
